---
title: "R4DS: Chapter 12 tidying data"
author: "daniel.lundin@lnu.se"
date: "`r format(Sys.time(), '%Y-%m-%d')`"
output:
    html_document:
        toc: yes
        toc_float:
          collapse: no
        fig_caption: yes
        code_folding: hide
    pdf_document:
        fig_caption: yes
        fig_height: 9
        fig_width: 8
        number_sections: yes
        toc: yes
bibliography:
    - grateful-refs.bib
---

```{r setup, echo=F, cache = FALSE}
knitr::opts_chunk$set(echo = TRUE, fig.path='figures/', cache = TRUE)
ggplot2::theme_set(ggplot2::theme_bw())
```

```{r libraries, message = FALSE, cache = FALSE, include = FALSE}
library(readr)
library(feather)
library(data.table)
library(dtplyr)
library(dplyr, warn.conflicts = FALSE)
library(tidyr)
library(purrr)
library(stringr)
library(ggplot2)
library(kfigr)
library(knitr)
library(DT)
library(grateful)
```

```{r constants}
```

```{r read-data-tax}
taxonomy <- read_tsv(
  'data/taxonomy_simple.tsv', 
  col_types = cols(seqname = col_character(), taxonomy = col_character())
) %>%
  mutate(taxonomy = str_remove_all(taxonomy, '[a-z]__')) %>%
  separate(taxonomy, c('domain', 'phylum', 'class', 'order', 'family', 'genus', 'species'), sep = ';')
```

```{r read-data-tax-dirty}
taxdirty <- read_tsv(
  'data/taxonomy_incomplete.tsv',
  col_types = cols(seqname = col_character(), taxonomy = col_character())
) %>%
  separate_rows(taxonomy, sep = ';') %>%
  separate(taxonomy, c('rank', 'taxon'), sep = '__') %>%
  pivot_wider(names_from = rank, values_from = taxon)
```

```{r rnr-comb-plot, fig.width = 12, fig.height = 6, fig.cap = '**These are the RNR combinations I found.**'}
read_tsv(
  'data/rnr_selection.tsv',
  show_col_types = FALSE
) %>%
  select(tdomain:pclass) %>%
  distinct() %>%
  pivot_wider(names_from = pclass, values_from = pclass) %>%
  unite('rnrs', NrdA, NrdD, NrdJ, sep = ':', na.rm = TRUE) %>%
  count(tdomain, tphylum, rnrs) %>%
  ggplot(aes(x = tphylum, y = n, colour = rnrs)) +
  geom_point() +
  coord_flip()
```


# Introduction

# Materials and Methods

## R and packages

This analysis was run with `r R.version$version.string`. Versions of packages used can be found in
`r figr('cite-packages', T, type = 'Table')`.

```{r cite-packages, cache = FALSE}
cite_packages(output = "table", pkgs = "Session") %>%
  kable()
```

# Results

# Discussion

# References
